# Generated by Django 5.1.5 on 2025-02-12 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0006_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedaccesstoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 0, 28, 43, 847726)),
        ),
    ]
