# Generated by Django 5.1.5 on 2025-02-12 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0007_remove_blacklistedaccesstoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 0, 29, 12, 851249)),
        ),
    ]
