# Generated by Django 5.1.5 on 2025-02-12 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0008_alter_blacklistedaccesstoken_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedaccesstoken',
            name='expiry',
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
