# Generated by Django 5.1.5 on 2025-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeanalytics',
            name='unique_user_list',
            field=models.JSONField(default=list),
        ),
    ]
